### ISSUE TITLE
How to enable and disable zoom functionality?

### ISSUE THREAD

**Issue by mattster09** [matabii/scale-imageview-android#2]
Hi, I am glad to have found out this project here. This is not an issue, it's more like I want to know the way to enable or disable ScaleImageview programmatically. Is it possible?

**Comment by gautiermichelin** [comment]
Hi Mattster09,

Just an idea, not tested, why not a double view, one with ScaleImageview, one ImageView and just a button switcher ?

**Comment by mattster09** [comment]
Hi, thanks for your reply here and sounds like a good idea. I will try that, even though my issue was resolved by using a whole different library i found. Thanks again!
